-- Create the rsvps table
create table rsvps (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  phone_number text not null unique,
  attending boolean not null,
  adults_count integer default 1,
  kids_count integer default 0
);

-- Enable Row Level Security (RLS)
alter table rsvps enable row level security;

-- Create a policy that allows anyone to insert (public RSVP)
create policy "Enable insert for everyone" on rsvps for insert with check (true);

-- Policy for updating based on phone number (simplified for client-side, insecure for production without auth)
create policy "Enable update for everyone" on rsvps for update using (true);
create policy "Enable select for everyone" on rsvps for select using (true);

-- Create the wishes table
create table wishes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  message text not null
);

-- Enable Row Level Security (RLS)
alter table wishes enable row level security;

-- Create policies for wishes
create policy "Enable insert for everyone" on wishes for insert with check (true);
create policy "Enable select for everyone" on wishes for select using (true);
